name: Release notes
description: 'Generate release notes for all the libraries inside given catalog.'

inputs:
  catalog:
    description: 'Versions Catalog .toml file name'
    required: true

runs:
  using: composite
  steps:
    - name: Validate input
      shell: bash
      run: |
        if [ -z ${{ inputs.catalog }} ]; then
          echo "Missing 'catalog' input or it is empty."
          exit 1
        elif [ ! -f ${{ inputs.catalog }} ]; then
          echo "${{ inputs.catalog }} catalog file not found."
          exit 1
        fi

    - name: Parse Catalog
      shell: bash
      run: |
        echo "Origin toml:"
        cat ${{ inputs.catalog }}
        echo "Parsed as json:"
        json=$(yq -j -oy '.' ${{ inputs.catalog }})
        echo "$json"
