name: Detekt check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  baselines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          ref: ${{ github.base_ref }}

      - name: Geberate baseline files
        run: |
          ./gradlew detektBaseline

      - name: Save baseline files
        uses: actions/upload-artifact@v3
        with:
          name: baseline-files
          path: ./**/detekt-baseline.xml

  detekt:
    needs: [ 'baselines' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Load baseline files
        uses: actions/download-artifact@v3
        with:
          name: baseline-files

      - name: Detekt
        continue-on-error: true
        run: |
          ./gradlew detekt

      - name: Save report files
        uses: actions/upload-artifact@v3
        with:
          name: detekt-reports
          path: |
            ./**/build/reports/detekt/detekt.txt
            ./**/build/reports/detekt/detekt.xml

  notify:
    needs: [ 'detekt' ]
    runs-on: ubuntu-latest
    steps:
      - name: Load report files
        uses: actions/download-artifact@v3
        with:
          name: detekt-reports

      - name: Find errors
        run: |
          # Gather array of reports
          reports=(`find . -name detekt.xml`)
          echo "${reports[@]}"
          
          for index in ${!reports[*]}; do
            file=${reports[index]}
            echo "File: ${file}"
            yq -p=xml --xml-attribute-prefix=attr_ -o=json '.file' ${file}
            json=$(yq -p=xml --xml-attribute-prefix=attr_ -o=json '.file' ${file})
          done
