name: Fix tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ORIGIN_ID: "31133766638e59e89d2067.47027901"
  COPY_ID: "9630074464025e8351c233.54116535"
  TOKEN: "b2ba155a823e5c460ced1fb4bc777e9aaf3d40f5"

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Single or comma separated Lokalise Key tag(s)'
        type: string
        default: "BAD_TAGS_NEED_FIXING"
        required: true

jobs:
  fix-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Lokalise CLI
        uses: sudosubin/setup-lokalise-action@v1.0.1
        with:
          lokalise-version: 'latest' # or specify version (ex. '2.6.3')

      - name: Revert broken tags
        run: |
          response_json=$(lokalise2 --token ${{ env.TOKEN }} --project-id ${{ env.ORIGIN_ID }} \
          key list --filter-platforms android --filter-tags "${{ github.event.inputs.tags }}")
          # Extract only 'key_id' values from 'keys' array
          broken_keys=$(jq -r '.keys[].key_name.android' <<< ${response_json})
          # Create array of broken keys ids
          broken_keys=(${broken_keys//$'\n'/ })
          keys_restored=0
          for counter in ${!broken_keys[*]}; do
            broken_key=${broken_keys[counter]}
            echo "${broken_key}"
            # Get broken key id
            origin_key_id=$(jq -r -c --arg key_name "${broken_key}" '.keys[] | select(.key_name.android == $key_name) | .key_id' <<< ${response_json})
            echo "${origin_key_id}"
            # Load correct tags for key 
            key_json=$(lokalise2 --token ${{ env.TOKEN }} --project-id ${{ env.COPY_ID }} \
            key list --filter-platforms android --filter-keys "${broken_key}")
            # Parse key tags
            tags_json=$(jq -r -c --arg key_name "${broken_key}" '.keys[] | select(.key_name.android == $key_name) | .tags' <<< ${key_json})
            echo "${tags_json[*]}"
            original_tags=$(jq -r -c --arg tag "${tag}" 'map(select(. != $tag))' <<< ${tags_json} | tr -d '[]"')
            echo "${original_tags}"
            # Update remote key tags
            lokalise2 --token ${{ env.TOKEN }} --project-id ${{ env.ORIGIN_ID }} \
            key update --key-id ${origin_key_id} --tags "${original_tags}" &> /dev/null
            # Increment counter
            keys_restored=$((keys_restored+1))
            echo "${keys_restored} processed."
          done
