name: Check dependencies health

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  pull_request:
  
jobs:
  Health_check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    
    - name: Check health
      id: check_health
      run: |
        ./gradlew buildHealth
        report_txt_file=build/reports/dependency-analysis/build-health-report.txt
        if [[ -f $report_txt_file && -s $report_txt_file ]]; then
          echo "Report .txt is successfully generated"
          echo report_txt_file=$report_txt_file >> $GITHUB_OUTPUT;
        else 
          echo "Report .txt is missing"
          echo report_txt_file= >> $GITHUB_OUTPUT;
        fi
        report_json_file=build/reports/dependency-analysis/build-health-report.json
        if [[ -f $report_json_file && -s $report_json_file ]]; then
          echo "Report .json is successfully generated"
          echo report_json_file=$report_json_file >> $GITHUB_OUTPUT;
        else 
          echo "Report .json is missing"
          echo report_json_file= >> $GITHUB_OUTPUT;
        fi
        
    - name: Report
      id: report
      if: ${{ steps.check_health.outputs.report_txt_file != '' && steps.check_health.outputs.report_json_file != '' }}
      continue-on-error: true
      run: |
        report_data="$(cat ${{ steps.check_health.outputs.report_json_file }})"
        report="$(cat ${{ steps.check_health.outputs.report_txt_file }})"
        echo "$report"
        delimiter="$(openssl rand -hex 8)"
        echo "report<<${delimiter}" >> ${GITHUB_OUTPUT}
        echo "$report" >> ${GITHUB_OUTPUT}
        echo "${delimiter}" >> ${GITHUB_OUTPUT}
        echo report_data=$report_data >> $GITHUB_OUTPUT
        exit 1
        
    - name: Generate comment message
      id: generate_comment_message
      if: ${{ steps.report.outputs.report != '' && steps.report.outputs.report_data != '' }}
      run: |
        unused_count=${{ fromJson(steps.report.outputs.report_data).unusedCount }}
        undeclared_count=${{ fromJson(steps.report.outputs.report_data).undeclaredCount }}
        mis_declared_count=${{ fromJson(steps.report.outputs.report_data).misDeclaredCount }}
        compile_only_count=${{ fromJson(steps.report.outputs.report_data).compileOnlyCount }}
        runtime_only_count=${{ fromJson(steps.report.outputs.report_data).runtimeOnlyCount }}
        processor_count=${{ fromJson(steps.report.outputs.report_data).processorCount }}
        
        unused_status=$([ $unused_count == 0 ] && echo ✅ || echo ❌ )
        undeclared_status=$([ $undeclared_count == 0 ] && echo ✅ || echo ❌ )
        mis_declared_status=$([ $mis_declared_count == 0 ] && echo ✅ || echo ❌ )
        compile_only_status=$([ $compile_only_count == 0 ] && echo ✅ || echo ❌ )
        runtime_only_status=$([ $runtime_only_count == 0 ] && echo ✅ || echo ❌ )
        processor_status=$([ $processor_count == 0 ] && echo ✅ || echo ❌ )
        
        message="## ⚠ Dependencies Health Check ⚠\n\n"
        message+="### Summary\n\n"

        message+="${unused_status} - Has no unused dependencies which should be removed (detected ${unused_count})\n"
        message+="${undeclared_status} - Has no transitively used dependencies that should be declared directly (detected ${undeclared_count})\n"
        message+="${mis_declared_status} - Has no existing dependencies which should be modified (detected ${mis_declared_count})\n"
        message+="${compile_only_status} - Has no dependencies which could be compile-only (detected ${compile_only_count})\n"
        message+="${runtime_only_status} - Has no dependencies which should be removed or changed to runtime-only (detected ${runtime_only_count})\n"
        message+="${processor_status} - Has no unused annotation processors that should be removed (detected ${processor_count})\n"
      
        message+="\nSee report below to get more insights.\n\n"
        message+="<details><summary>Report</summary>\n\n"
        message+="#### ${{ github.event.repository.name }} health check report:\n\n"
        message+="${{ steps.report.outputs.report }}\n\n"
        message+="</details>"
        
        echo -e "$message"
        delimiter="$(openssl rand -hex 8)"
        echo "message<<${delimiter}" >> ${GITHUB_OUTPUT}
        echo -e "$message" >> ${GITHUB_OUTPUT}
        echo "${delimiter}" >> ${GITHUB_OUTPUT}
        
    - name: Comment on PR
      if: ${{ steps.generate_comment_message.outputs.message != '' }}
      uses: mshick/add-pr-comment@v2
      with:
        message-id: health_check
        message: ${{ steps.generate_comment_message.outputs.message }}
          
