name: Sync strings with Lokalise

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  #schedule:
    #- cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  Sync-string-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Lokalise CLI
      uses: sudosubin/setup-lokalise-action@v1.0.1
      with:
        lokalise-version: 'latest' # or specify version (ex. '2.6.3')

    - name: Checkout
      uses: actions/checkout@v3.1.0
      
    - name: Read project name
      id: read_project_name
      run: |
        raw_project_name=$(./gradlew -q printProjectName)
        # Convert to lowercase and replace white spaces with '-'
        processed_project_name=$(echo $raw_project_name | tr " " "-" | tr '[:upper:]' '[:lower:]')
        echo project_name=$processed_project_name >> $GITHUB_OUTPUT

    - name: Pull strings from Lokalise
      continue-on-error: true
      run: |
        # Get paths to all "res" folders
        arr=(`find . -type d -name res`)
        for counter in ${!arr[*]}; do
          res_path=${arr[counter]}
          # Get module from path, by cutting "/src/..." part out of original path
          module_path=${res_path%%/src/*}
          # Replace "." in module path with project name to generate tag that consists of
          # project name and module path 
          tag=${module_path/./${{ steps.read_project_name.outputs.project_name }}}
          echo "Pulling translations tagged \"${tag}\" into \"${module_path}\" module..."
          # Call Lokalise CLI (v2) "file download" command to pull all available translations 
          # (tagged with the tag we generated before) and unzip them to a proper module.
          lokalise2 --token ${{ secrets.LOKALISE_TOKEN }} --project-id ${{ secrets.LOKALISE_PROJECT_ID }} file download --export-empty-as skip --export-sort first_added --format xml --include-tags $tag --unzip-to "${module_path}/src/main/res" --directory-prefix "values-%LANG_ISO%" --original-filenames false
        done
        
    - name: Push strings to Lokalise
      run: |
        # Get paths to all "strings.xml" files
        arr=(`find . -type f -name strings.xml`)
        for counter in ${!arr[*]}; do
          file_path=${arr[counter]}
          # Get module from path, by cutting "/src/..." part out of original path
          module_path=${file_path%%/src/*}
          # Get path to /values" (/values-Lang_ISO) folder 
          folder_path=$(dirname ${file_path})
          # Get suffix of /values-Lang_ISO folder (result "-Lang_ISO")
          folder_suffix=${folder_path##*values}
          # Remove '-' from suffix
          lang_iso=${folder_suffix#-}
          # Replace "." in module path with project name to generate tag that consists of
          # project name and module path 
          tag=${module_path/./${{ steps.read_project_name.outputs.project_name }}}
          echo "Pushing \"${lang_iso:-en}\" strings from \"${module_path}\" module with \"${tag}\" tag..."
          # Call Lokalise CLI (v2) "file upload" command to upload 'strings.xml' file. 
          # Each string key is tagged with the tag we generated, so later on (while pulling)
          # script understands where pulled translations should be unzipped to
          lokalise2 --token ${{ secrets.LOKALISE_TOKEN }} --project-id ${{ secrets.LOKALISE_PROJECT_ID }} file upload --file $file_path --lang-iso ${lang_iso:-en} --tag-skipped-keys --tags $tag
        done

    - name: Check changes
      id: check_changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Changes detected"
          echo changes_detected=true >> $GITHUB_OUTPUT;
        else 
          echo "Changes not detected"
          echo changes_detected=false >> $GITHUB_OUTPUT;
        fi

    - name: Check branch exists
      id: check_branch_exists
      continue-on-error: true
      run: |
        git ls-remote --exit-code --heads origin 'lokalise/sync_translations' >/dev/null 2>&1
        RESULT=$?
        if [[ $RESULT == '0' ]]; then
          echo "Branch exists"
          echo branch_exists=true >> $GITHUB_OUTPUT;
        elif [[ $RESULT == '2' ]]; then
          echo "Branch does not exist"
          echo branch_exists=false >> $GITHUB_OUTPUT;
        fi

    - name: Checkout Lokalise branch
      if: ${{ steps.check_branch_exists.outputs.branch_exists == 'true' }}
      uses: actions/checkout@v3.1.0
      with:
        ref: lokalise/sync_translations

    - name: Push changes
      id: push_changes
      if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}
      uses: devops-infra/action-commit-push@v0.9.2
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        commit_prefix: "Update "
        commit_message: "Lokalise translations"
        force: false
        target_branch: lokalise/sync_translations

    - name: Create PR
      if: ${{ steps.push_changes.outputs.files_changed != '' }}
      uses: devops-infra/action-pull-request@v0.5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: lokalise/sync_translations
        target_branch: main
        title: "Lokalise: Translations update"
        #reviewer: octocat
        #assignee: octocat
        label: lokalise
        #draft: true
        get_diff: true
