name: Sync strings with Lokalise

on: 
  #schedule:
    #- cron: '*/15 * * * *'
  workflow_dispatch:
  
    
jobs: 
  lokalise:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Lokalise CLI
      uses: sudosubin/setup-lokalise-action@v1.0.1
      with:
        lokalise-version: 'latest' # or specify version (ex. '2.6.3')
        
    - name: Checkout
      uses: actions/checkout@v3.1.0
        
    - name: Pull strings from Lokalise
      run: >
        lokalise2
        --token ${{ secrets.LOKALISE_TOKEN }}
        --project-id ${{ secrets.LOKALISE_PROJECT_ID }}
        file download
        --export-empty-as skip
        --export-sort first_added
        --format xml
        --unzip-to "app/src/main/res"
        --directory-prefix "values-%LANG_ISO%"
        --original-filenames false
        
    - name: Check changes
      run: |
        if [[ `git status --porcelain` ]]; then
        export CHANGES_DETECTED=true 
        else export CHANGES_DETECTED=false
        fi
        echo CHANGES_DETECTED >> $GITHUB_ENV
    
    - name: Push changes
      if: ${{ env.CHANGES_DETECTED == 'true' }}
      run: |
        git config --global user.email "vlohachov-ecw@cricut.com"
        git config --global user.name "vlohachov"
        git checkout -b lokalise/sync_translations
        git add --all
        git commit -m "Update: Lokalise translations"
        git push origin lokalise/sync_translations
        export CHANGES_PUSHED=true
        echo CHANGES_PUSHED >> $GITHUB_ENV
        
    - name: Create PR
      if: ${{ env.CHANGES_PUSHED == 'true' }}
      uses: devops-infra/action-pull-request@v0.5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: development
        target_branch: master
        title: "Lokalise: Translations update"
        #template: .github/PULL_REQUEST_TEMPLATE.md
        #body: "**Automated pull request**"
        #reviewer: octocat
        #assignee: octocat
        label: lokalise
        #milestone: My milestone
        #draft: true
        #old_string: "<!-- Add your description here -->"
        #new_string: "** Automatic pull request**"
        get_diff: true
