name: Sync strings with Lokalise

on: 
  #schedule:
    #- cron: '*/15 * * * *'
  workflow_dispatch:
    
jobs: 
  Sync-string-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Lokalise CLI
      uses: sudosubin/setup-lokalise-action@v1.0.1
      with:
        lokalise-version: 'latest' # or specify version (ex. '2.6.3')
        
    - name: Checkout
      uses: actions/checkout@v3.1.0
      
    - name: Push strings to Lokalise
      run: |
        arr=(*/src/main/res/values*/strings.xml)
        for counter in ${!arr[*]}; do
          file_path=${arr[counter]}
          module=${file_path%%/*/*}
          folder_path=$(dirname ${file_path})
          folder_suffix=${folder_path##*values}
          lang_iso=${folder_suffix#-}
          echo ${module}
          echo ${file_path}
          echo ${lang_iso:-en}
          lokalise2 --token ${{ secrets.LOKALISE_TOKEN }} --project-id ${{ secrets.LOKALISE_PROJECT_ID }} file upload --file $file_path --lang-iso ${lang_iso:-en} --tag-skipped-keys --tags $module
        done
        
    - name: Pull strings from Lokalise
      run: |
        arr=(*/src/main/res)
        for counter in ${!arr[*]}; do
          file_path=${arr[counter]}
          module=${file_path%%/*/*}
          echo ${module}
          #lokalise2 --token ${{ secrets.LOKALISE_TOKEN }} --project-id ${{ secrets.LOKALISE_PROJECT_ID }} file download --export-empty-as skip --export-sort first_added --format xml --unzip-to "${module}/src/main/res" --directory-prefix "values-%LANG_ISO%" --original-filenames false
        done
        
    - name: Check changes
      id: check_changes
      if: false
      run: |
        if [[ `git status --porcelain` ]]; then
          echo changes_detected=true >> $GITHUB_OUTPUT;
        else 
          echo changes_detected=false >> $GITHUB_OUTPUT;
        fi
    
    - name: Push changes
      id: push_changes
      if: false
      #if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}
      uses: devops-infra/action-commit-push@v0.9.2
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        commit_prefix: "Update "
        commit_message: "Lokalise translations"
        force: false
        target_branch: lokalise/sync_translations
        
    - name: Create PR
      if: ${{ steps.push_changes.outcome == 'success' }}
      uses: devops-infra/action-pull-request@v0.5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: lokalise/sync_translations
        target_branch: main
        title: "Lokalise: Translations update"
        #template: .github/PULL_REQUEST_TEMPLATE.md
        #body: "**Automated pull request**"
        #reviewer: octocat
        #assignee: octocat
        label: lokalise
        #milestone: My milestone
        #draft: true
        #old_string: "<!-- Add your description here -->"
        #new_string: "** Automatic pull request**"
        get_diff: true
