name: Metalava compatibility check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  metalava-compatibility-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master/main
        uses: actions/checkout@v3.1.0
        with:
          ref: main # or master

      - name: Generate signature files
        run: |
          ./gradlew metalavaGenerateSignature metalavaGenerateSignatureDebug

      - name: Print apis
        run: |
          files=(`find . -type f -name *-api.txt`)
          echo "${files[@]}"

      - name: Save signature files
        uses: actions/upload-artifact@v3
        with:
          path: ~/**/api/

      - name: Checkout current
        uses: actions/checkout@v3.1.0

      - name: Load signature files
        uses: actions/download-artifact@v3
        with:
          path: ~/**/api/

      - name: Print apis
        run: |
          files=(`find . -type f -name *-api.txt`)
          echo "${files[@]}"

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Check Kotlin libs compatibility
        id: check-compat-kotlin
        run: |
          if ./gradlew metalavaCheckCompatibility 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibility FAILED'; then
            errors=$(grep -oP '(?<=error: ).*' gradle_output.log | paste -sd ',')
            errors=$(sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" <<< "$errors")
            echo compat-errors=$errors >> $GITHUB_OUTPUT;
          fi

      - name: Check Android libs compatibility
        id: check-compat-android
        run: |
          if ./gradlew metalavaCheckCompatibilityDebug 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibilityDebug FAILED'; then
            errors=$(grep -oP '(?<=error: ).*' gradle_output.log | paste -sd ',')
            errors=$(sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" <<< "$errors")
            echo compat-errors=$errors >> $GITHUB_OUTPUT;
          fi

      - name: Combine possible compatibility errors
        id: combine-compat-errors
        run: |
          combined_errors=""
          
          # Append Kotlin libs compat errors
          if [[ "${{ steps.check-compat-kotlin.outputs.compat-errors }}" != "" ]]; then
            combined_errors+="${{ steps.check-compat-kotlin.outputs.compat-errors }}"
          fi
          
          # Append Android libs compat errors
          if [[ "${{ steps.check-compat-android.outputs.compat-errors }}" != "" ]]; then
            if [[ combined_errors != "" ]]; then
              combined_errors+=","
            fi
            combined_errors+="${{ steps.check-compat-android.outputs.compat-errors }}"
          fi
          
          echo combined-compat-errors=$combined_errors >> $GITHUB_OUTPUT;

      - name: Generate PR body appendix message
        id: appendix-message
        if: ${{ steps.combine-compat-errors.outputs.combined-compat-errors != '' }}
        run: |
          # Create bash array of combined errors
          IFS=',' read -ra errors_arr <<< "${{ steps.combine-compat-errors.outputs.combined-compat-errors }}"
          
          # Group errors by module
          declare -A module_errors
          for error in "${errors_arr[@]}"; do
            module=$(echo "${error}" | sed -E 's/.* ([^ ]+)\..*/\1/')
            if [[ ! "${module_errors[$module]}" ]]; then
              module_errors[$module]="- ${error}"
            else
              module_errors[$module]+=$'\n'"- ${error}"
            fi
          done
          
          echo incompatible_modules_count=${#module_errors[@]} >> ${GITHUB_OUTPUT}
          
          # Details with errors grouped by module
          message=$(
            for module in "${!module_errors[@]}"; do
              echo "#### ${module}:"
              echo "${module_errors[$module]}"
            done
          )
          
          delimiter="$(openssl rand -hex 8)"
          echo "message<<${delimiter}" >> ${GITHUB_OUTPUT}
          echo "$message" >> ${GITHUB_OUTPUT}
          echo "${delimiter}" >> ${GITHUB_OUTPUT}

      - name: Update PR (title & body)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          appendix_message="${{ steps.appendix-message.outputs.message }}"
          
          # Get PR title
          gh pr view ${{ github.event.number }} --json title > pr_title.json
          pr_title=$(jq -r '.title' pr_title.json)
          
          # Get PR body
          gh pr view ${{ github.event.number }} --json body > pr_body.json
          pr_body=$(jq -r '.body' pr_body.json)
          
          # Update PR title
          pr_prefix="BREAKING: "

          # Add prefix if not yet added and appendix is not empty
          if [[ "${pr_title}" != "${pr_prefix}"* ]] && [[ -n "${appendix_message}" ]]; then
            pr_title="${pr_prefix}${pr_title}"
          # Remove prefix if added and appendix is empty
          elif [[ "${pr_title}" == "${pr_prefix}"* ]] && [[ -z "${appendix_message}" ]]; then
            pr_title="${pr_title/#${pr_prefix}/}"
          fi
          gh pr edit ${{ github.event.number }} --title "${pr_title}"
          
          # Update PR body
          issues_section="### ❗ Compatibility Issues ❗"
          # Remove old appendix if present
          if grep -q "${issues_section}" <<< "${pr_body}"; then
            pr_body=$(sed "/${issues_section}/,\$d" <<< "${pr_body}")
          fi
          # Add appendix if not empty
          if [[ -n "${appendix_message}" ]]; then
            incompatible_modules="${{ steps.appendix-message.outputs.incompatible_modules_count }} incompatible modules detected"
            pr_body_appendix="${issues_section}"$'\n'"${incompatible_modules}"$'\n'"${appendix_message}"
            pr_body="${pr_body}"$'\n\n'"${pr_body_appendix}"
          fi
          gh pr edit ${{ github.event.number }} --body "${pr_body}"
