name: Metalava

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  metalava-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Check Kotlin libs compatibility
        id: compat-kotlin
        continue-on-error: true
        run: |
          if ./gradlew metalavaCheckCompatibility 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibility FAILED'; then
            echo "::set-output name=compat-errors::$(grep -oP '(?<=error: ).*' gradle_output.log | paste -sd ',')"
            exit 1
          fi

      - name: Check Android libs compatibility
        id: compat-android
        continue-on-error: true
        run: |
          if ./gradlew metalavaCheckCompatibilityDebug 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibilityDebug FAILED'; then
            echo "::set-output name=compat-errors::$(grep -oP '(?<=error: ).*' gradle_output.log | paste -sd ',')"
            exit 1
          fi

      - name: Combine possible compatibility errors
        id: combine-compat-errors
        if: ${{ always() }}
        continue-on-error: true
        run: |
          combined_errors=""
          if [[ "${{ steps.compat-kotlin.outputs.compat-errors }}" != "" ]]; then
            combined_errors+="${{ steps.compat-kotlin.outputs.compat-errors }}"
          fi
          if [[ "${{ steps.compat-android.outputs.compat-errors }}" != null ]]; then
            if [[ combined_errors != "" ]]; then
              combined_errors+=","
            fi
            combined_errors+="${{ steps.compat-android.outputs.compat-errors }}"
          fi
          echo "::set-output name=combined-compat-errors::combined_errors"

      - name: Update PR with errors
        if: ${{ steps.combine-compat-errors.outputs.combined-compat-errors != "" }}
        run: |
          message=""
          
          IFS=',' read -ra errors_arr <<< "${{ steps.combine-compat-errors.outputs.combined-compat-errors }}"

          # Group errors by module
          declare -A module_errors
          for error in "${errors_arr[@]}"; do
            module=$(echo "${error}" | sed -E 's/.* ([^ ]+)\..*/\1/')
            if [[ ! "${module_errors[$module]}" ]]; then
              module_errors[$module]="${error}"
            else
              module_errors[$module]+=$'\n'"${error}"
            fi
          done
          
          # Print errors grouped by module
          for module in "${!module_errors[@]}"; do
            message+="${module}:"
            message+="${module_errors[$module]}"
          done
          
          echo "$message"
