name: Metalava compatibility check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  metalava-compatibility-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Check Kotlin libs compatibility
        id: check-compat-kotlin
        run: |
          if ./gradlew metalavaCheckCompatibility 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibility FAILED'; then
            errors=$(grep -oP '(?<=error: ).*' gradle_output.log | paste -sd ',')
            errors=$(sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" <<< "$errors")
            echo compat-errors=$errors >> $GITHUB_OUTPUT;
          fi

      - name: Check Android libs compatibility
        id: check-compat-android
        run: |
          if ./gradlew metalavaCheckCompatibilityDebug 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibilityDebug FAILED'; then
            errors=$(grep -oP '(?<=error: ).*' gradle_output.log | paste -sd ',')
            errors=$(sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" <<< "$errors")
            echo compat-errors=$errors >> $GITHUB_OUTPUT;
          fi

      - name: Combine possible compatibility errors
        id: combine-compat-errors
        run: |
          combined_errors=""
          
          # Append Kotlin libs compat errors
          if [[ "${{ steps.check-compat-kotlin.outputs.compat-errors }}" != "" ]]; then
            combined_errors+="${{ steps.check-compat-kotlin.outputs.compat-errors }}"
          fi
          
          # Append Android libs compat errors
          if [[ "${{ steps.check-compat-android.outputs.compat-errors }}" != "" ]]; then
            if [[ combined_errors != "" ]]; then
              combined_errors+=","
            fi
            combined_errors+="${{ steps.check-compat-android.outputs.compat-errors }}"
          fi
          
          echo combined-compat-errors=$combined_errors >> $GITHUB_OUTPUT;

      - name: Update PR
        if: ${{ steps.combine-compat-errors.outputs.combined-compat-errors != '' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get PR title
          gh pr view ${{ github.event.number }} --json title > pr_title.json
          pr_title=$(jq -r '.title' pr_title.json)
          pr_prefix="BREAKING:"
          
          # Update PR title if needed
          if ! [[ "$pr_title" =~ "$pr_prefix" ]]; then
            pr_title="$pr_prefix ${pr_title}"
            gh pr edit ${{ github.event.number }} --title "${pr_title}"
          fi
          
          # Create bash array of combined errors
          IFS=',' read -ra errors_arr <<< "${{ steps.combine-compat-errors.outputs.combined-compat-errors }}"
          
          # Group errors by module
          declare -A module_errors
          for error in "${errors_arr[@]}"; do
            module=$(echo "${error}" | sed -E 's/.* ([^ ]+)\..*/\1/')
            if [[ ! "${module_errors[$module]}" ]]; then
              module_errors[$module]="${error}"
            else
              module_errors[$module]+=$'\n'"${error}"
            fi
          done
          
          # Details with errors grouped by module
          details_header="<details><summary>Compatibility errors</summary><p>"
          details_footer="</p></details>"
          errors=$(
            for module in "${!module_errors[@]}"; do
              echo "${module}:"
              echo "${module_errors[$module]}"
            done
          )
          
          # Get PR body
          gh pr view ${{ github.event.number }} --json body > pr_body.json
          pr_body=$(jq -r '.body' pr_body.json)
          
          # Update PR body
          if echo "$pr_body" | grep -qF "$details_header" && echo "$pr_body" | grep -qF "$details_footer"; then
            # Replace substring between header and footer with errors
            pr_body=$(echo "$pr_body" | sed "/$details_header/,/$details_footer/c\\$details_header\n$errors\n$details_footer")
          else 
            pr_body="${pr_body}"$'\n\n'"$details_header"$'\n'"$errors"$'\n'"$details_footer"
          fi
          gh pr edit ${{ github.event.number }} --body "${pr_body}"
