name: Metalava

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  metalava-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Check compatibility (Kotlin)
        id: compat-kotlin
        continue-on-error: true
        run: |
          if ./gradlew metalavaCheckCompatibility 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibility FAILED'; then
            echo "::set-output name=compat-error::$(grep -oP '(?<=error: ).*' gradle_output.log)"
            exit 1
          fi

      - name: Check compatibility (Android)
        id: compat-android
        continue-on-error: true
        run: |
          if ./gradlew metalavaCheckCompatibilityDebug 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibilityDebug FAILED'; then
            echo "::set-output name=compat-error::$(grep -oP '(?<=error: ).*' gradle_output.log)"
            exit 1
          fi

      - name: Check for breaking change
        if: ${{ always() }}
        run: |
          if [[ "${{ steps.compat-kotlin.outcome }}" == "failure" ]]; then
            echo "One or more Kotlin libraries have a breaking change."
            echo "${{ steps.compat-kotlin.outputs.compat-error }}"
          else
            echo "No breaking changes detected (Kotlin)."
          fi
          if [[ "${{ steps.compat-android.outcome }}" == "failure" ]]; then
            echo "One or more Android libraries have a breaking change."
            echo "${{ steps.compat-android.outputs.compat-error }}"
          else
            echo "No breaking changes detected (Android)."
          fi
