name: Metalava

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  metalava-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Check compatibility (Kotlin)
        id: compat-kotlin
        continue-on-error: true
        run: |
          if ./gradlew metalavaCheckCompatibility 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibility FAILED'; then
            echo "::set-output name=compat-error::$(grep -oP '(?<=error: ).*' gradle_output.log | paste -sd ',')"
            exit 1
          fi

      - name: Check compatibility (Android)
        id: compat-android
        continue-on-error: true
        run: |
          if ./gradlew metalavaCheckCompatibilityDebug 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibilityDebug FAILED'; then
            echo "::set-output name=compat-error::$(grep -oP '(?<=error: ).*' gradle_output.log | paste -sd ',')"
            exit 1
          fi

      - name: Check for breaking change
        if: ${{ always() }}
        run: |
          # Extract errors from compat-error output into an array
          errors=($(echo "${{ steps.compat-kotlin.outputs.compat-error }} ${{ steps.compat-android.outputs.compat-error }}" | tr ',' '\n' | tr -d '[]'))
          echo "${errors[*]}"
          # Print each error
          for error in "${errors[@]}"; do
            echo "$error"
          done
