name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Get version
        id: get-version
        run: |
          versions_and_sha=$(
            gh api -X GET /repos/${{ github.repository }}/git/matching-refs/tags/ \
              | jq -r '.[] | select(.ref | test("^refs/tags/v.*")) | .ref[10:] + " " + .object.sha' \
              | sort -V -r \
              | head -n 1
          )
          latest_version=$(echo "$versions_and_sha" | awk '{print $1}')
          latest_commit_sha=$(echo "$versions_and_sha" | awk '{print $2}')
          echo "Latest release tag: ${latest_version}"
          echo "Latest release sha: ${latest_commit_sha}"
          echo version=${latest_version} >> $GITHUB_OUTPUT;

      - name: Check for breaking changes
        run: |
          latest_release_sha=$(git rev-list -n 1 ${{ steps.get-version.outputs.version }})
          echo "${latest_release_sha}"
#          gh api repos/${{ github.repository }}/commits --paginate

      - name: Publish
        if: false
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish
