name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Get version
        id: get-version
        run: |
          latest_version=$(
            gh api -X GET /repos/${{ github.repository }}/git/matching-refs/tags/ \
              | jq -r '.[].ref' \
              | grep -E '^refs/tags/v.*' \
              | sed 's/^refs\/tags\///' \
              | sort -V -r \
              | head -n 1
          )
          echo "Latest release tag: ${latest_version}"
          
          
          #export VERSION=${LATEST_RELEASE_TAG:1}
          #echo "VERSION=${VERSION}" >> $GITHUB_ENV
          #echo "Detected Version is '${VERSION_NAME}'"
          echo version=$latest_version >> $GITHUB_OUTPUT;

      - name: Check for breaking changes
        run: |
          gh api repos/${{ github.repository }}/commits

      - name: Publish
        if: false
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish
