name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Get latest release TAG
        id: get-tag
        run: |
          latest_release_tag=$(git for-each-ref --sort=-committerdate --format='%(refname:short)' 'refs/tags/v*' | head -n 1)
          echo "Latest release tag: ${latest_release_tag}"
          echo tag=${latest_release_tag} >> $GITHUB_OUTPUT;

      - name: Check for breaking changes
        run: |
          tag=${{ steps.get-tag.outputs.tag }}
          git log ${tag}..HEAD --format=%B --grep="BREAKING CHANGE: "

      - name: Publish
        if: false
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish
