name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LATEST_RELEASE_TAG=$(
            gh api -X GET /repos/vlohachov/LokaliseAutomation/git/matching-refs/tags/ \
              | jq -r '.[].ref' \
              | grep -E '^refs/tags/v.*' \
              | sed 's/^refs\/tags\///' \
              | sort -V -r \
              | head -n 1
          )
          echo "${LATEST_RELEASE_TAG}"
          #export LATEST_RELEASE_TAG=${GITHUB_REF/refs\/tags\//}
          #export VERSION=${LATEST_RELEASE_TAG:1}
          #echo "VERSION=${VERSION}" >> $GITHUB_ENV
          #echo "Detected Version is '${VERSION_NAME}'"

      - name: Publish
        if: false
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish
