name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Get latest release TAG and SHA
        id: tag-and-sha
        run: |
          tag_and_sha=$(
            gh api -X GET /repos/${{ github.repository }}/git/matching-refs/tags/ \
              | jq -r '.[] | select(.ref | test("^refs/tags/v.*")) | .ref[10:] + " " + .object.sha' \
              | sort -V -r \
              | head -n 1
          )
          tag=$(echo "${tag_and_sha}" | awk '{print $1}')
          sha=$(echo "${tag_and_sha}" | awk '{print $2}')
          echo "Latest release tag: ${tag}"
          echo "Latest release sha: ${sha}"
          echo tag=${tag} >> $GITHUB_OUTPUT;
          echo sha=${sha} >> $GITHUB_OUTPUT;

      - name: Check for breaking changes
        run: |
          tag=${{ steps.tag-and-sha.outputs.tag }}
          sha=${{ steps.tag-and-sha.outputs.sha }}
          #gh api repos/${{ github.repository }}/commits --paginate
          commits=$(
            gh api repos/${{ github.repository }}/commits --paginate \
              -q ".[] | {sha: .sha, message: .commit.message}"
          )
          commits_since_sha=$(echo "$commits" | awk -v start_sha="$sha" 'BEGIN {found=0} {if (found || $2 == start_sha) {found=1; next} print}')

          echo "Commits since ${tag}:"
          echo "${commits_since_sha}"

      - name: Publish
        if: false
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish
