name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Get latest release TAG and SHA
        id: tag-and-sha
        run: |
          tag_and_sha=$(
            gh api -X GET /repos/${{ github.repository }}/git/matching-refs/tags/ \
              | jq -r '.[] | select(.ref | test("^refs/tags/v.*")) | .ref[10:] + " " + .object.sha' \
              | sort -V -r \
              | head -n 1
          )
          tag=$(echo "${tag_and_sha}" | awk '{print $1}')
          sha=$(echo "${tag_and_sha}" | awk '{print $2}')
          echo "Latest release tag: ${tag}"
          echo "Latest release sha: ${sha}"
          echo tag=${tag} >> $GITHUB_OUTPUT;
          echo sha=${sha} >> $GITHUB_OUTPUT;

      - name: Check for breaking changes
        run: |
          tag=${{ steps.tag-and-sha.outputs.tag }}
          sha=${{ steps.tag-and-sha.outputs.sha }}
          commits=$(
            gh api repos/${{ github.repository }}/commits --paginate \
              -q '[.[] | {sha: .sha, message: .commit.message}]'
          )
          
          # Convert JSON array to Bash associative array
          declare -A commit_map
          while IFS=$'\t' read -r key message; do
            commits_map["$key"]="$message"
          done < <(echo "$commits" | jq -r '.[] | "\(.sha)\t\(.message)"')
          
          # Example usage: print all shas and messages
          for key in "${!commits_map[@]}"; do
            if [[ $key == $sha ]]; then break
            echo "SHA: $key"
            echo "Message: ${commits_map[$key]}"
          done

      - name: Publish
        if: false
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish
