name: Create new release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major'
        type: boolean
        required: false
        default: false
      minor:
        description: 'Minor'
        type: boolean
        required: false
        default: false
      patch:
        description: 'Patch'
        type: boolean
        required: false
        default: false
      alpha:
        description: 'Alpha'
        type: boolean
        required: false
        default: false
      rc:
        description: 'RC'
        type: boolean
        required: false
        default: false

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      latest-stable-version: ${{ steps.latest-stable-version.outputs.version }}
      current-version: ${{ steps.current-version.outputs.version }}
      new-version: ${{ steps.new-version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Release type
        id: release-type
        run: |
          if [[ ${{ github.event.inputs.alpha }} == 'true' ]]; then
            value='alpha'
          elif [[ ${{ github.event.inputs.rc }} == 'true' ]]; then
            value='rc'
          else
            value='stable'
          fi
          echo value=${value} >> $GITHUB_OUTPUT;

      - name: Latest stable version
        id: latest-stable-version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          releases=$(gh release list --exclude-drafts --exclude-pre-releases | awk '{print $1}')
          sorted=$(echo "${releases}" | sort -Vr)
          echo "List of sorted releases:"
          echo "${sorted}"
          latest_stable_version=$(echo "${sorted}" | head -1)
          echo "Latest stable version: ${latest_stable_version}"
          echo version=${latest_stable_version:1} >> $GITHUB_OUTPUT;

      - name: Current version
        id: current-version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          releases=$(gh release list --exclude-drafts | awk '{print $1}')
          sorted=$(echo "${releases}" | sort -Vr)
          echo "List of sorted releases:"
          echo "${sorted}"
          
          if [[ ${{ github.ref_name }} == *"release"* ]]; then
            base_version=${{ github.ref_name }}
            base_version="v${base_version#*/}"
            current_version=$(echo "${sorted}" | awk -v rel="${base_version%.*}" -v RS="\n" -v ORS="\n" 'BEGIN {p=0} {if(index($0,rel)==1)p=1; if(p) print}' | head -1)
          else 
            current_version=$(echo "${sorted}" | head -1)
          fi
          
          if [[ ${current_version} == *"${{ steps.latest-stable-version.outputs.version }}"* ]]; then
            current_version="v${{ steps.latest-stable-version.outputs.version }}"
          fi
          
          echo "Current version: ${current_version}"
          echo version=${current_version:1} >> $GITHUB_OUTPUT;

      - name: Check for breaking changes
        id: breaking-changes
        run: |
          breaking_commits=$(git log v${{ steps.current-version.outputs.version }}..HEAD --format=%B --grep="BREAKING CHANGE: ")
          if [[ ${breaking_commits} != "" ]]; then
            result=true
          fi
          echo result=${result:-false} >> $GITHUB_OUTPUT;

      - name: New version
        id: new-version
        uses: vlohachov/LokaliseAutomation/.github/actions/new-version@main
        with:
          current-version: ${{ steps.current-version.outputs.version }}
          major-increment: ${{ github.event.inputs.major == 'true' || steps.breaking-changes.outputs.result == 'true' }}
          minor-increment: ${{ github.event.inputs.minor }}
          patch-increment: ${{ github.event.inputs.patch }}
          alpha-increment: ${{ github.event.inputs.alpha }}
          rc-increment: ${{ github.event.inputs.rc }}

      - name: Fail if version already released
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version_tag=v${{ steps.new-version.outputs.new-version }}
          if gh release view ${version_tag} >/dev/null 2>&1; then
            echo "Release ${version_tag} already exists."
            exit 1
          fi

  publish:
    if: false
    needs: [ update-version ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Publish
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.update-version.outputs.new-version }}
        run: |
          ./gradlew publish

  release:
    needs: [ update-version, publish ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release type
        id: release-type
        run: |
          if [[ ${{ github.event.inputs.alpha }} == 'true' ]]; then
            value='alpha'
          elif [[ ${{ github.event.inputs.rc }} == 'true' ]]; then
            value='rc'
          else
            value='stable'
          fi
          echo value=${value} >> $GITHUB_OUTPUT; 

      - name: Create stable release
        if: ${{ steps.release-type.outputs.value == 'stable' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v${{ needs.update-version.outputs.new-version }} \
          --target ${{ github.ref_name }} \
          --generate-notes --notes-start-tag v${{ needs.update-version.outputs.latest-stable-version }}

      - name: Create pre release
        if: ${{ steps.release-type.outputs.value != 'stable' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v${{ needs.update-version.outputs.new-version }} --prerelease \
          --target ${{ github.ref_name }} \
          --generate-notes --notes-start-tag v${{ needs.update-version.outputs.current-version }}
