name: Create new release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      check-maven:
        description: 'Check maven'
        type: boolean
        required: false
        default: false
      major:
        description: 'Major'
        type: boolean
        required: false
        default: false
      minor:
        description: 'Minor'
        type: boolean
        required: false
        default: false
      patch:
        description: 'Patch'
        type: boolean
        required: false
        default: false
      alpha:
        description: 'Alpha'
        type: boolean
        required: false
        default: false
      rc:
        description: 'RC'
        type: boolean
        required: false
        default: false

jobs:
  release:
    if: ${{ github.event.inputs.check-maven == 'false' }}
    uses: cricut/release/.github/workflows/release.yml@v2.0.1
    secrets: inherit
    with:
      major: ${{ github.event.inputs.major == 'true' }} # (optional: default false) increments major number
      minor: ${{ github.event.inputs.minor == 'true' }} # (optional: default false) increments minor number
      patch: ${{ github.event.inputs.patch == 'true' }} # (optional: default false) increments patch number
      alpha: ${{ github.event.inputs.alpha == 'true' }} # (optional: default false) increments alpha number
      rc: ${{ github.event.inputs.rc == 'true' }} # (optional: default false) increments rc number
      java-version: '17' # (optional) JDK version

  check-maven:
    if: ${{ github.event.inputs.check-maven == 'true' }}
    runs-on: android
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check maven local
        run: |
          ls -al ~/.m2/repository
