name: Scripts testing

on:
  workflow_dispatch:

jobs:
  update-gradle-properties:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update gradle.properties
        run: |
          # Define the function
          my_function() {
            echo "This is a function call for $1..."
            # Simulate some work
            sleep 2

            if [[ $1 == +(item4|item5) ]]; then
              echo "Function call for $1 failed!"
              return 1
            else
              echo "Function call for $1 finished!"
              return 0
            fi
          }

          items=("item1" "item2" "item3" "item4" "item5" "item6" "item7" "item8" "item9" "item10")

          echo "Setting up semaphore..."
          # Max concurrent jobs
          MAX_JOBS=4
          # Semaphore setup
          SEMAPHORE=$(mktemp -u)  # Create a unique name for the semaphore
          mkfifo "$SEMAPHORE"
          exec 3<>"$SEMAPHORE"
          rm "$SEMAPHORE"
          for _ in $(seq $MAX_JOBS); do echo >&3; done

          for item in "${items[@]}"; do
            # Wait for an available slot in the semaphore
            read -u 3
            (
              # Call the function
              is_success=$(my_function $item)

              echo "is_success=$is_success"

              echo >&3  # Release the slot after the job is done
            ) &
          done

          wait
          
          exec 3>&-
          
          echo "Complete!"
