name: Scripts testing

on:
  workflow_dispatch:

jobs:
  update-gradle-properties:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update gradle.properties
        run: |
          # Print project root ./gradle.properties
          cat ./gradle.properties
          echo "-----------------------------------------------------------------------------------"
          # Override gradle internal http timeouts
          echo "systemProp.org.gradle.internal.http.connectionTimeout=120000" >> ./gradle.properties
          echo "systemProp.org.gradle.internal.http.socketTimeout=120000" >> ./gradle.properties
          # Override gradle parallel 
          sed -i 's/^org.gradle.parallel=true/org.gradle.parallel=false/' ./gradle.properties
          # Print modified project root ./gradle.properties
          cat ./gradle.properties
          echo "-----------------------------------------------------------------------------------"
