name: Scripts testing

on:
  workflow_dispatch:

jobs:
  update-gradle-properties:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update gradle.properties
        run: |
          # Define the function
          my_function() {
            echo "This is a function"
            # Simulate some work
            sleep 2
          }

          # Call the function
          my_function

          # More script execution
          echo "Doing more work"
          sleep 1

          # Exit cleanly
          exit 0
