name: Scripts testing

on:
  workflow_dispatch:

jobs:
  update-gradle-properties:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update gradle.properties
        run: |
          cat ./gradle.properties
