name: Scripts testing

on:
  workflow_dispatch:

jobs:
  update-gradle-properties:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update gradle.properties
        run: |
          # Define the function
          my_function() {
            echo "This is a function call for $1"
            # Simulate some work
            sleep 2
          }

          items=("first" "second" "third" "fourth" "fifth")

          for item in "${items[@]}"; do
            (
              # Call the function
              my_function $item
            ) &
          done

          wait

          echo "Complete!"
